# Generated by Django 3.1.5 on 2021-01-15 19:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Category Coupon',
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Category Product',
            },
        ),
        migrations.CreateModel(
            name='VendorCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Vendor Coupon',
            },
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Vendor Product',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('categoryProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoryproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('categoryProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoryproduct')),
                ('subcategoryProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subcategoryproduct')),
                ('vendorProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendorproduct')),
            ],
            options={
                'verbose_name_plural': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('categoryCoupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categorycoupon')),
                ('vendorCoupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendorcoupon')),
            ],
            options={
                'verbose_name_plural': 'Coupon',
            },
        ),
    ]
