# Generated by Django 3.1.5 on 2021-01-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210115_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='check',
            field=models.BooleanField(default=True),
        ),
    ]
